name = "geist-web"
compatibility_date = "2025-05-08"
compatibility_flags = ["nodejs_compat"]

workers_dev = false

routes = [
   { pattern = "filecoin.geist.network", zone_name = "geist.network" },
    { pattern = "filecoin.geist.network/*", zone_name = "geist.network" }
 ]


[vars]
HOST = "https://filecoin.geist.network"


[observability.logs]
enabled = false