name = "geist-web"
compatibility_date = "2025-05-08"
compatibility_flags = ["nodejs_compat"]

workers_dev = false

# Option 1: Custom domain (requires domain setup in Cloudflare)
routes = [
   { pattern = "filecoin.geist.network/auth/callback", custom_domain = true },
   { pattern = "filecoin.geist.network", custom_domain = true }
 ]


[vars]
HOST = "https://filecoin.geist.network"

# Option 2: Cloudflare zone route
# routes = [
#   { pattern = "example.com/*", zone_name = "example.com" }
# ]