name = "websocket-server"
main = "./src/index.ts"
compatibility_date = "2025-05-08"
# compatibility_flags = ["nodejs_compat"]


[vars]
LIVESTORE_CF_SYNC_DATABASE_ID = "9b7a07d6-88d6-4663-9dae-a3b1de63450c"


[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebSocketServer"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketServer"]

[[d1_databases]]
binding = "DB"
database_name = "livestore-sync-cf-demo"
database_id = "${LIVESTORE_CF_SYNC_DATABASE_ID}"
