// Generated by React Router

import "react-router";

declare module "react-router" {
	interface Register {
		pages: Pages;
		routeFiles: RouteFiles;
	}
}

type Pages = {
	"/": {
		params: {};
	};
	"/auth/callback": {
		params: {};
	};
	"/client-metadata.json": {
		params: {};
	};
};

type RouteFiles = {
	"root.tsx": {
		id: "root";
		page: "/" | "/auth/callback" | "/client-metadata.json";
	};
	"routes/_index.tsx": {
		id: "routes/_index";
		page: "/";
	};
	"routes/auth.callback.tsx": {
		id: "routes/auth.callback";
		page: "/auth/callback";
	};
	"routes/client-metadata[.]json.tsx": {
		id: "routes/client-metadata[.]json";
		page: "/client-metadata.json";
	};
};
